DATASET:
  # ROOT:  '/shared/tale2/Shared/data/EgoAction/'
  SOURCE: 'EPIC100'
#  SRC_TRAINLIST: 'EPIC_100_uda_source_train.pkl'
#  SRC_TESTLIST: 'EPIC_100_uda_source_test_timestamps.pkl'
  SRC_TRAINLIST: 'val/EPIC_100_uda_source_train.pkl'
  SRC_TESTLIST: 'val/EPIC_100_uda_source_test_timestamps.pkl'
  TARGET: 'EPIC100'
#  TGT_TRAINLIST: 'EPIC_100_uda_target_train_timestamps.pkl'
#  TGT_TESTLIST: 'EPIC_100_uda_target_test_timestamps.pkl'
  TGT_TRAINLIST: 'val/EPIC_100_uda_target_train_timestamps.pkl'
  TGT_TESTLIST: 'val/EPIC_100_uda_target_test_timestamps.pkl'
  IMAGE_MODALITY: 'rgb'
  INPUT_TYPE: 'feature'
  NUM_SEGMENTS: 16
  FRAMES_PER_SEGMENT: 1
